apiVersion: apps/v1
kind: Deployment
metadata:
  name: deconz
  namespace: deconz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deconz
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: deconz
    spec:
      nodeSelector:
        kubernetes.io/hostname: harmen-rpi-ssd
      containers:
        - name: deconz
          image: deconzcommunity/deconz:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          env:
            - name: TZ
              value: Europe/Amsterdam
            - name: DECONZ_DEVICE
              value: /dev/serial/by-id/deconz
          securityContext:
            privileged: true
          volumeMounts:
            - name: config
              mountPath: /opt/deCONZ
            - name: usb
              mountPath: /dev/serial/by-id/deconz
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: deconz-data
        - name: usb
          hostPath:
            path: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2456829-if00
            type: CharDevice
