apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deconz
  namespace: deconz
spec:
  ingressClassName: traefik
  rules:
    - host: deconz.home.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: deconz
                port:
                  name: http
