apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zwavejs
  namespace: zwavejs
spec:
  ingressClassName: traefik
  rules:
    - host: zwavejs.home.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zwavejs
                port:
                  name: http
    - host: websockets.zwavejs.home.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zwavejs
                port:
                  name: websocket
