apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zwavejs
configMapGenerator:
  - name: zwavejs-settings
    files:
      - config/settings.json
      - config/node-names.json
generatorOptions:
  disableNameSuffixHash: true
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - secret-securitykeys.yaml
