apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zigbee2mqtt
configMapGenerator:
  - name: zigbee2mqtt-config
    files:
      - config/configuration.yaml
generatorOptions:
  disableNameSuffixHash: true
resources:
  - namespace.yaml
  - pvc.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - onboarding.yaml
