- platform: template
  buttons:
    harmen_dimmer_diningtable_secondary_single:
      name: "Eettafel – secondary single"
    harmen_dimmer_diningtable_secondary_double:
      name: "Eettafel – secondary double"
    harmen_dimmer_diningtable_secondary_triple:
      name: "Eettafel – secondary triple"