input_button:
  HARMEN-DIMMER-DININGTABLE-SECONDARY-SINGLE:
    name: HARMEN-DINNER-DINIGTABLE-SECONDARY-SINGLE
  HARMEN-DIMMER-DININGTABLE-SECONDARY-DOUBLE:
    name: HARMEN-DINNER-DINIGTABLE-SECONDARY-DOUBLE