alias: HARMEN-DIMMER-DININGTABLE - S2 Scenes
use_blueprint:
  path: zwavejs_fibaro_dimmer2_scenes.yaml
  input:
    zwavejs_device: HARMEN-DIMMER-DININGTABLE
    s2_once:
      - service: input_button.press
        target:
          entity_id: input_button.harmen_dimmer_diningtable_secondary_single
    s2_twice:
      - service: input_button.press
        target:
          entity_id: input_button.harmen_dimmer_diningtable_secondary_double
