apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infra/flux-system
  - infra/stakater-reloader
  - infra/traefik
  - apps/mosquitto
  - apps/grafana
  - apps/deconz
  - apps/zwavejs
  - apps/zigbee2mqtt
  - apps/homeassistant

  
