apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infra/flux-system
  - infra/stakater-reloader
  - infra/traefik
  - infra/cert-manager
  - apps/mosquitto
  - apps/grafana
  # - apps/deconz # disabled because only one app can use usb
  - apps/zwavejs 
  - apps/zigbee2mqtt
  - apps/homeassistant

  
