# load basic home-assistant configuration
default_config:

# Settings for instance
homeassistant:
  name: Thuis
  latitude: 52.15869
  longitude: 4.50890
  unit_system: metric
  time_zone: Europe/Amsterdam
  country: NL
  language: nl

# Configure Home Assistant to work behind a reverse proxy
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.42.0.0/16 # traefik internal network
    - 127.0.0.1/32 # localhost

# frontend:
#   themes: !include_dir_merge_named themes

# automation: !include automations.yaml
# script: !include scripts.yaml
# scene: !include scenes.yaml
