light.harmen_dimmer_diningtable:
  friendly_name: "Lamp eettafel"
  icon: "mdi:chandelier"
light.harmen_dimmer_diningtable_2:
  friendly_name: "Schakelaar eettafel"
  device_class: input_button
  disabled: false