light.harmen_dimmer_diningtable:
  friendly_name: Lamp eettafel
  icon: mdi:chandelier
light.harmen_dimmer_diningtable_2:
  friendly_name: Schakelaar eettafel
  device_class: button
  enabled: false
light.harmen_dimmer_hallway:
  friendly_name: Lamp gang
  icon: mdi:ceiling-light