  - name: HK-BRDG-CLIMATE
    port: 21065
    filter:
      include_domains:
        - climate
  - name: HK-BRDG-LIGHTS
    port: 21066
    filter:
      include_domains:
        - light
  - name: HK-BRDG-SWITCHES
    port: 21067
    filter:
      include_domains:
        - switch
  - name: HK-BRDG-INPUT-BUTTONS
    port: 21068
    filter:
      include_domains:
        - input_button
  - name: HK-BRDG-BUTTONS
    port: 21069
    filter:
      include_domains:
        - button
  - name: HK-BRDG-MOTION
    port: 21070
    filter:
      include_domains:
        - binary_sensor
        - sensor
      include_device_classes:
        - motion
        - illuminance