  - name: HK-BRDG-CLIMATE
    port: 21065
    filter:
      include_domains:
        - climate
  - name: HK-BRDG-LIGHTS
    port: 21066
    filter:
      include_domains:
        - light
  - name: HK-BRDG-SWITCHES
    port: 21067
    filter:
      include_domains:
        - switch
      exclude_entity_globs:
        - switch.*kinderslot
  - name: HK-BRDG-BUTTONS
    port: 21068
    filter:
      include_domains:
        - input_button
        - button
  - name: HK-BRDG-MOTION
    port: 21070
    filter:
      include_entity_globs:
      - binary_sensor.*motion*
      - sensor.*motion*