  - name: HOMEKIT-BRDG-CLIMATE
    port: 21065
    filter:
      include_domains:
        - climate
  - name: HOMEKIT-BRDG-LIGHTS
    port: 21066
    filter:
      include_domains:
        - light
  - name: HOMEKIT-BRDG-SWITCHES
    port: 21067
    filter:
      include_domains:
        - switch
  - name: HOMEKIT-BRDG-INPUT-BUTTONS
    port: 21068
    filter:
      include_domains:
        - input_button