apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: homeassistant
  namespace: homeassistant
configMapGenerator:
  - name: ha-config
    files:
      - config
generatorOptions:
  disableNameSuffixHash: true
