apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homeassistant
configMapGenerator:
  - name: ha-config
    files:
      - config/configuration.yaml
      - config/homekit.yaml
      - config/mqtt.yaml
  - name: ha-blueprints
    files:
      - blueprints/automation/zwavejs_fibaro_dimmer2_scenes.yaml=config/blueprints/automation/zwavejs_fibaro_dimmer2_scenes.yaml
  - name: ha-automations
    files:
      - automations/dimmer/harmen_dining_table.yaml=config/automations/dimmers/harmen_dimmer_diningtable.yaml
  - name: ha-helpers
    files:
      - helpers/input_buttons.yaml=config/helpers/input_buttons.yaml
  
generatorOptions:
  disableNameSuffixHash: true
resources:
  - namespace.yaml
  - pvc.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - onboarding.yaml
