apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homeassistant
configMapGenerator:
  - name: ha-config
    files:
      - config/configuration.yaml
      - config/homekit.yaml
      - config/mqtt.yaml
      - config/blueprints/automation/zwavejs/fibaro_dimmer2_scenes.yaml
generatorOptions:
  disableNameSuffixHash: true
resources:
  - namespace.yaml
  - pvc.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - onboarding.yaml
