apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homeassistant
configMapGenerator:
  - name: ha-config
    files:
      - config/configuration.yaml
      - config/homekit.yaml
      - config/mqtt.yaml
      - config/customize.yaml
  - name: ha-blueprints-automation
    files:
      - config/blueprints/automation/zwavejs_fibaro_dimmer2_scenes.yaml
      - config/blueprints/automation/dynamic_light_based_on_presence_and_illuminance.yaml
  - name: ha-automation-dimmers
    files:
      - config/automation/dimmers/harmen_dimmer_diningtable.yaml
  - name: ha-automation-motion
    files:
      - config/automation/motion/motion_light_hallway.yaml
  - name: ha-helpers
    files:
      - config/helpers/input_buttons.yaml
      - config/helpers/buttons.yaml
  
generatorOptions:
  disableNameSuffixHash: true
resources:
  - namespace.yaml
  - pvc.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - onboarding.yaml
